pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                bat 'echo Running basic validation...'
                bat 'if exist index.html (echo index.html found) else exit /b 1'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t devops-task-manager:%BUILD_NUMBER% .'
            }
        }

        stage('Run Docker Container') {
            steps {
                bat 'docker rm -f devops-container || exit 0'
                bat 'docker run -d -p 8083:80 --name devops-container devops-task-manager:%BUILD_NUMBER%'
            }
        }

        stage('Cleanup') {
            steps {
                bat 'docker image prune -f'
            }
        }

        stage('Generate HTML Report') {
            steps {
                bat '''
                if not exist reports mkdir reports

                (
                echo ^<html^>
                echo ^<head^>
                echo ^<title^>Jenkins Build Report^</title^>
                echo ^<style^>
                echo body { font-family: Arial; margin:40px; background:#f4f4f4; }
                echo h1 { color:#2E8B57; }
                echo table { border-collapse: collapse; width:60%%; }
                echo th, td { border:1px solid #ddd; padding:10px; }
                echo th { background:#2E8B57; color:white; }
                echo .success { color:green; font-weight:bold; }
                echo ^</style^>
                echo ^</head^>
                echo ^<body^>
                echo ^<h1^>DevOps Task Manager - Jenkins Build Report^</h1^>
                echo ^<table^>
                echo ^<tr^>^<th^>Item^</th^>^<th^>Value^</th^>^</tr^>
                echo ^<tr^>^<td^>Build Number^</td^>^<td^>%BUILD_NUMBER%^</td^>^</tr^>
                echo ^<tr^>^<td^>Job Name^</td^>^<td^>%JOB_NAME%^</td^>^</tr^>
                echo ^<tr^>^<td^>Build URL^</td^>^<td^>%BUILD_URL%^</td^>^</tr^>
                echo ^<tr^>^<td^>Docker Image^</td^>^<td^>devops-task-manager:%BUILD_NUMBER%^</td^>^</tr^>
                echo ^<tr^>^<td^>Container Name^</td^>^<td^>devops-container^</td^>^</tr^>
                echo ^<tr^>^<td^>Application Port^</td^>^<td^>8083^</td^>^</tr^>
                echo ^<tr^>^<td^>Pipeline Status^</td^>^<td class="success"^>SUCCESS^</td^>^</tr^>
                echo ^</table^>
                echo ^<br/^>
                echo ^<h2^>Pipeline Stages Completed^</h2^>
                echo ^<ul^>
                echo ^<li^>Checkout^</li^>
                echo ^<li^>Test^</li^>
                echo ^<li^>Build Docker Image^</li^>
                echo ^<li^>Run Docker Container^</li^>
                echo ^<li^>Cleanup^</li^>
                echo ^<li^>Generate HTML Report^</li^>
                echo ^</ul^>
                echo ^<p^>Generated by Jenkins Pipeline automatically after build completion.^</p^>
                echo ^</body^>
                echo ^</html^>
                ) > reports\\index.html
                '''
            }
        }
    }

    post {
        always {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'reports',
                reportFiles: 'index.html',
                reportName: 'Build Report'
            ])
        }

        success {
            echo 'CI/CD pipeline completed successfully.'
        }

        failure {
            echo 'CI/CD pipeline failed.'
        }
    }
}
